---
version: '2'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment: 
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_PID: Standard
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: "Y"

  connect:
    image: cdc:latest
    depends_on:
      - sqlserver
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: #kafka server : port
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: soder-kfk-connect-1-config-1
      CONNECT_CONFIG_STORAGE_TOPIC: soder-kfk-connect-1-config
      CONNECT_OFFSET_STORAGE_TOPIC: soder-kfk-connect-1-offsets
      CONNECT_STATUS_STORAGE_TOPIC: soder-kfk-connect-1-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_OFFSET.STORAGE.REPLICATION.FACTOR: 1
      CONNECT_CONFIG.STORAGE.REPLICATION.FACTOR: 1
      CONNECT_OFFSET.STORAGE.PARTITIONS: 1
      CONNECT_STATUS.STORAGE.REPLICATION.FACTOR: 1
      CONNECT_STATUS.STORAGE.PARTITIONS: 1
      CONNECT_REST_ADVERTISED_HOST_NAME: #kafka server without port